[package]
name = "rxcolors"
version = "0.1.0"
authors = ["Antti Lamminsalo <antti.lamminsalo@gmail.com>"]

[dependencies]
futures = "0.1"
hyper = "0.11"
hyper-tls = "0.1.2"
tokio-core = "0.1"
serde_json = "*"
